export const sample_items = [
  {
    id: 10001,
    name: "black bean",
    quantity: "10",
    description: "(some description)",
    commodity_category: "commodity category A",
    sub_category: "sub category A",
    commodity_product: "commodity product A",
  },
  {
    id: 10002,
    name: "yellow bean",
    quantity: "10",
    description: "(some description)",
    commodity_category: "commodity category B",
    sub_category: "sub category B",
    commodity_product: "commodity product B",
  },
  {
    id: 10003,
    name: "grey bean",
    quantity: "10",
    description: "(some description)",
    commodity_category: "commodity category C",
    sub_category: "sub category C",
    commodity_product: "commodity product C",
  },
  {
    id: 10004,
    name: "black bean",
    quantity: "10",
    description: "(some description)",
    commodity_category: "commodity category A",
    sub_category: "sub category A",
    commodity_product: "commodity product A",
  },
  {
    id: 10005,
    name: "yellow bean",
    quantity: "10",
    description: "(some description)",
    commodity_category: "commodity category B",
    sub_category: "sub category B",
    commodity_product: "commodity product B",
  },
  {
    id: 10006,
    name: "grey bean",
    quantity: "10",
    description: "(some description)",
    commodity_category: "commodity category C",
    sub_category: "sub category C",
    commodity_product: "commodity product C",
  },
  {
    id: 10007,
    name: "black bean",
    quantity: "10",
    description: "(some description)",
    commodity_category: "commodity category A",
    sub_category: "sub category A",
    commodity_product: "commodity product A",
  },
  {
    id: 10008,
    name: "yellow bean",
    quantity: "10",
    description: "(some description)",
    commodity_category: "commodity category B",
    sub_category: "sub category B",
    commodity_product: "commodity product B",
  },
  {
    id: 10009,
    name: "grey bean",
    quantity: "10",
    description: "(some description)",
    commodity_category: "commodity category C",
    sub_category: "sub category C",
    commodity_product: "commodity product C",
  },
  {
    id: 10010,
    name: "grey bean",
    quantity: "10",
    description: "(some description)",
    commodity_category: "commodity category C",
    sub_category: "sub category C",
    commodity_product: "commodity product C",
  },
];
